# Generated by Django 4.1.2 on 2022-10-28 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_desde', models.DateField(default=datetime.date(2022, 10, 28))),
                ('fecha_hasta', models.DateField(null=True)),
            ],
        ),
    ]
